AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  S3 Synapse sync lambda

Parameters:
  SynapseProjectId:
    Description: 'The Synapse project ID'
    Type: String
    ConstraintDescription: >-
      Synapse ID of project; an identifier with the format syn12345678
  SynapseFoldersToSync:
    Description: 'The list of Synapse folders to sync'
    Type: CommaDelimitedList
    ConstraintDescription: >-
      Comma separated list of folders in bucket to be synchronized to Synapse

Resources:
  S3SynapseLambdaExecute:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
            - logs:*
          Resource: arn:aws:logs:*:*:*
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:PutObjectAcl
          Resource: arn:aws:s3:::*

  SSMParameterStore:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
           - ssm:DescribeParameters
          Resource: "*"
        - Effect: Allow
          Action:
            - ssm:GetParameters
            - ssm:GetParameter
          Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/HTAN/SynapseSync/*"

  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3_synapse_sync/
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      Role: !GetAtt FunctionRole.Arn
      Timeout: 900
      MemorySize: 320
      Environment:
        Variables:
          SYNAPSE_PROJECT_ID: !Ref SynapseProjectId
          SYNAPSE_FOLDERS_TO_SYNC: !Ref SynapseFoldersToSync

  FunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - !Ref SSMParameterStore
        - !Ref S3SynapseLambdaExecute
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-htan-synapse-sync-kms-key-KmsDecryptPolicyArn'

Outputs:
  FunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt Function.Arn
  FunctionRoleArn:
    Description: "Lambda function role ARN"
    Value: !GetAtt FunctionRole.Arn
